site_name: Uni Resumos
theme:
  name: material
  features:
    - navigation.path
    - toc.follow
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
repo_url: https://github.com/eduardoschulz/uni-resumos/
plugins:
    - search
    - pdf-export
    - awesome-pages
    - git-committers:
        repository: eduardoschulz/uniresumos
        token: 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
        branch: master
        #https://github.com/ojacques/mkdocs-git-committers-plugin-2
    # git-authors
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML
markdown_extensions:
  - mdx_math

